rulebender_online/mysite/urls.py
from django.conf.urls import include, url
from django.contrib   import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^ajaxa/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

rulebender_online/polls/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$',             views.IndexView.as_view(), name='index'),
    url(r'^zero_no_key/$', views.zero_no_key, name='zero_no_key'),
    url(r'^cmap/$',        views.cmap,       name='cmap'),
    url(r'^cone/$',        views.cone,       name='cone'),
    url(r'^pmap/$',        views.pmap,       name='pmap'),
    url(r'^parse/$',       views.parse,      name='parse'),
    url(r'^cmap_key/$',    views.cmap_key,   name='cmap_key'),
    url(r'^comp_key/$',    views.comp_key,   name='comp_key'),
    url(r'^cone_key/$',    views.cone_key,   name='cone_key'),
    url(r'^pmap_key/$',    views.pmap_key,   name='pmap_key'),
    url(r'^pone_key/$',    views.pone_key,   name='pone_key'),
    url(r'^oone_key/$',    views.oone_key,   name='oone_key'),
    url(r'^omap_key/$',    views.omap_key,   name='omap_key'),
    url(r'^parse_key/$',   views.parse_key,  name='parse_key'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

rulebender_online/polls/models.py
from __future__ import unicode_literals

  
import datetime


from django.db import models
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):               
        return self.choice_text

rulebender_online/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.http import *
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import RequestContext
from ipware.ip import get_real_ip
from subprocess import Popen, PIPE
from subprocess import  call
from django.http import HttpResponse
from ctypes import get_errno
from .models import Choice, Question
import json 
import socket
import datetime
import time
import subprocess
import StringIO
import csv
import urllib2
import xml.etree.cElementTree as ET
import sys
import errno, os
import time
import fcntl

from os.path import expanduser
home = expanduser("~")
data_root = '%s/d_rulebender_data' % home
util_root = data_root + '/d_utilities'


class Payload(object):
    def __init__(self, j):
        self.__dict__ = json.loads(j)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

""" ------------- SECOND UPLOAD OF DATA --------------------------- """
""" This anticipates a session key in the first line of the file """
""" This anticipates a model name in the second line of the file """
""" This anticipates zero parameters """
def zero_key(request,python_map_type):
    global util_root
    global data_root

    print('  ')
    print('  ')
    print('  ')
    print('---------------- Calling zero_key -------------------------')

    x_bngl = request.POST['client_response']

    key_end = x_bngl.find("\n")
    x_session = x_bngl[0:key_end]

    name_end = x_bngl.find("\n",key_end+1)
    x_name   = x_bngl[key_end+1:name_end]
    x_bngl   = x_bngl[name_end+1:]


    print (" zero_key   x_name = " + x_name)
    # Hmmm...  There's no longer a need to speculate on what the correct
    # month is.
    p = Popen('date "+%m"', shell=True, stdout=PIPE, stderr=PIPE)
    y_month   = p.stdout.read().strip()
    p = Popen(home + '/d_rulebender_data/d_utilities/s_get_month  ' +
              y_month + '  ' + x_session, shell=True, stdout=PIPE, 
              stderr=PIPE)
    x_month   = p.stdout.read().strip()
    if x_month == 'not_found':
        return zero_no_key(request,python_map_type)
    else:
        # Do we need dir_head ?
        results_head = home + "/d_rulebender_data/" \
                   + x_month + "/" + x_session + "/d_results"

        # The working directory will have a name that is based on the date.
        working_dir = getCurrentWorkDir(x_session)
        if working_dir == 'not_found':
           working_dir = createOutputDirectory(results_head,"next")

        # If there's any important activity, create new directory.
        if os.path.isfile(working_dir + "/non_parse_activity.txt"):
           print(" Creating new directory ")
           working_dir = createOutputDirectory(results_head,"next")

        data_head = working_dir + "/input_file.bngl"
        file = open(data_head, "w")
        file.write(x_bngl)
        file.close()

        full_tag = getFullTag(results_head)
        print(" full_tag: " + full_tag)
        

        print("Calling zero_key driver")
        util_script = util_root + "/s_driver"
        os.system(util_script + " " + x_month + " " + x_session + " " + \
           full_tag + " " + python_map_type)


        lindex = getIndex(results_head)
        ltag   = getTag(results_head)
        time_cpu     = 0.0
        time_elapsed = 0.0
        dir_head = data_root + "/" + x_month + "/" + x_session
        loadTrackingData(dir_head,x_name,time_cpu,time_elapsed, \
           python_map_type,ltag,lindex)


        y_bngl = ' dummy content '
        """
         Let's not worry about this now.  
        """ 
        con_head = dir_head + "/d_results/" + full_tag + "/d_work"
        result_file =  con_head + "/layout_elements.txt" 
        file = open(result_file, "r")
        y_bngl = file.read()
        file.close()

        z_bngl = y_bngl + "    \n      session_key_51937      \n   " + x_session
        return HttpResponse(z_bngl, content_type='text/plain')


def pmap(request):
    if request.POST.has_key('client_response'):
        return zero_no_key(request,"ruleviz_pattern") 
    else:
        template_name = 'polls/index.html'

def cmap(request):
    if request.POST.has_key('client_response'):
        return zero_no_key(request,"contactmap") 
    else:
        template_name = 'polls/index.html'

def cone(request):
    if request.POST.has_key('client_response'):
        return zero_no_key(request,"ruleviz_operation_one") 
    else:
        template_name = 'polls/index.html'

def parse(request):
    if request.POST.has_key('client_response'):
        return zero_no_key(request,"parse") 
    else:
        template_name = 'polls/index.html'

def parse_key(request):
    if request.POST.has_key('client_response'):
        return zero_key(request,"parse") 
    else:
        template_name = 'polls/index.html'

def cmap_key(request):
    if request.POST.has_key('client_response'):
        return zero_key(request,"contactmap") 
    else:
        template_name = 'polls/index.html'

def pmap_key(request):
    if request.POST.has_key('client_response'):
        return zero_key(request,"ruleviz_pattern") 
    else:
        template_name = 'polls/index.html'

def comp_key(request):
    if request.POST.has_key('client_response'):
        return zero_key(request,"ruleviz_operation") 
    else:
        template_name = 'polls/index.html'

def cone_key(request):
    if request.POST.has_key('client_response'):
        return one_key(request,"ruleviz_operation_one") 
    else:
        template_name = 'polls/index.html'

def omap_key(request):
    if request.POST.has_key('client_response'):
        return zero_key(request,"regulatory") 
    else:
        template_name = 'polls/index.html'

def oone_key(request):
    if request.POST.has_key('client_response'):
        return one_key(request,"regulatory_one") 
    else:
        template_name = 'polls/index.html'


""" ------------- SECOND UPLOAD OF DATA --------------------------- """
""" This anticipates a session key in the first line of the file """
""" This anticipates a model name in the second line of the file """
""" This anticipates one parameter in the third line """
def one_key(request,python_map_type):

    print('  ')
    print('  ')
    print('  ')
    print('---------------- Calling one_key -------------------------')

    x_bngl = request.POST['client_response']

    key_end = x_bngl.find("\n")
    x_session = x_bngl[0:key_end]

    name_end = x_bngl.find("\n",key_end+1)
    x_name   = x_bngl[key_end+1:name_end]

    aux_end   = x_bngl.find("\n",name_end+1)
    aux_value = x_bngl[name_end+1:aux_end]

    x_bngl   = x_bngl[aux_end+1:]
  
    """ 
    file = open("/home/roc60/d_contactmap/session.txt", "w")
    file.write(x_bngl)
    file.close()
    """ 

    p = Popen('date "+%m"', shell=True, stdout=PIPE, stderr=PIPE)
    y_month   = p.stdout.read().strip()
    p = Popen(home + '/d_rulebender_data/d_utilities/s_get_month  ' +
              y_month + '  ' + x_session, shell=True, stdout=PIPE, 
              stderr=PIPE)
    x_month   = p.stdout.read().strip()
    if x_month == 'not_found':
        y_bngl = 'Request for one_no_key() not yet implemented.'
    else:
        """ Create director for this data set. """
        # Do we need dir_head ?
        results_head = home + "/d_rulebender_data/" \
                   + x_month + "/" + x_session + "/d_results"

        # The working directory will have a name that is based on the date.
        working_dir = getCurrentWorkDir(x_session)
        if working_dir == 'not_found':
           working_dir = createOutputDirectory(results_head,"next")

        # If there's any important activity, create new directory.
        if os.path.isfile(working_dir + "/non_parse_activity.txt"):
           print(" Creating new directory ")
           working_dir = createOutputDirectory(results_head,"next")

        data_head = working_dir + "/input_file.bngl"
        file = open(data_head, "w")
        file.write(x_bngl)
        file.close()



        full_tag = getFullTag(results_head)
        print(" full_tag: " + full_tag)
        

        print("Calling zero_key driver")
        util_script = util_root + "/s_driver"
        os.system(util_script + " " + x_month + " " + x_session + " " + \
           full_tag + " " + python_map_type + " " + aux_value)


        lindex = getIndex(results_head)
        ltag   = getTag(results_head)
        time_cpu     = 0.0
        time_elapsed = 0.0
        dir_head = data_root + "/" + x_month + "/" + x_session
        loadTrackingData(dir_head,x_name,time_cpu,time_elapsed, \
           python_map_type,ltag,lindex)


        y_bngl = ' dummy content '
        """
         Let's not worry about this now.  
        """ 
        con_head = dir_head + "/d_results/" + full_tag + "/d_work"
        result_file =  con_head + "/layout_elements.txt" 
        file = open(result_file, "r")
        y_bngl = file.read()
        file.close()

        z_bngl = y_bngl + "    \n      session_key_51937      \n   " + x_session
        return HttpResponse(z_bngl, content_type='text/plain')





def pone_key(request):
    if request.POST.has_key('client_response'):
        return one_key(request,'ruleviz_pattern_one')
    else:
        template_name = 'polls/index.html'


""" ------------- FIRST UPLOAD OF DATA --------------------------- """
""" This does not anticipate a session key at the head of the file """
""" It does expect a model name at the head of the file """
""" Instead, it creates a session key, and sends it back """
def zero_no_key(request,python_map_type):
    global util_root

    print('  ')
    print('  ')
    print('  ')

rulebender_online/polls/templates/polls/detail.html
{% include "polls/header.html" %}



<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

rulebender_online/polls/templates/polls/index.html
<!-- <div class="basic">  -->
{% include "polls/header.html" %}    
<!-- </div>  -->




<style type="text/css">
      .CodeMirror {border: 1px solid #aaa; height: 400px; width: 700px; font-weight: 900;}
<!--
      .lineblock { display: inline-block; margin: 1px; height: 5px; }
-->
      .cm-bngl_comment      { color: grey;   }
      .cm-bngl_section      { color: purple; }
      .cm-bngl_observables  { color: purple; }
      .cm-bngl_red          { color: red;    }
      .cm-bngl_blue         { color: blue;   }
      .cm-bngl_green        { color: green;  }
      .cm-bngl_orange       { color: orange; }

      .styled-background       { background-color: #ff7; }
      .CodeMirror-selected     { background-color: blue !important; }
      .CodeMirror-selectedtext { color: white; }
      .note-gutter             { width: 0.6em; background: white; }
      .rhc-gutter              { width: 0.6em; background: white; }


ul.tab {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    border: 1px solid #ccc;
    background-color: #f1f1f1;
}

/* Float the list items side by side */
ul.tab li {float: left;}

/* Style the links inside the list items */
ul.tab li a {
    display: inline-block;
    color: black;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    transition: 0.3s;
    font-size: 17px;
}

/* Change background color of links on hover */
ul.tab li a:hover {background-color: #ddd;}

/* Create an active/current tablink class */
ul.tab li a:focus, .active {background-color: #ccc;}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 6px 12px;
    border: 1px solid #ccc;
    border-top: none;
}



</style>









<div id="container-fluid">  
<div class="row">
<div class="col-lg-6">

<div class="row" >
  <ul class="tab" style="padding:0px 0px 0px 10px">
    <li><a href="javascript:void(0)" class="tablinks" id="b1" 
           onclick="openCity(event, 'London')">Open</a></li>
    <li><a href="javascript:void(0)" class="tablinks" id="b2" 
           onclick="openCity(event, 'Paris')">Save</a></li>
    <li><a href="javascript:void(0)" class="tablinks" id="b3" 
           onclick="openCity(event, 'Tokyo')">Simulate</a></li>
    <li><a href="javascript:void(0)" class="tablinks" id="b4" 
           onclick="openCity(event, 'Clear')">Close</a></li>
  </ul>

  <div id="London" class="tabcontent">
    <h3>London</h3>
    <p>London is the capital city of England.</p>
  </div>

  <div id="Paris" class="tabcontent">
    <h3>Paris</h3>
    <p>Paris is the capital of France.</p>
  </div>

  <div id="Tokyo" class="tabcontent">
    <h3>Tokyo</h3>
    <p>Tokyo is the capital of Japan.</p>
  </div>

  <div id="Clear" class="clearcontent"> </div>
</div>             <!-- row 1 of col 1 -->

<div class="row" style="background-color:#f1f1f1; padding:15px 10px 10px 27px">  
    <!-- row 2 of col 1 -->
    {% include "polls/div_edit.html" %}    
</div> <!-- row 2 of col 1 -->


</div> <!-- end of col 1 -->
<div class="col-lg-6">  <!-- col 2 -->
<div class="row"> 
  <ul class="tab">
    <li><a href="javascript:void(0)" class="tablinks" id="c1" 
           onclick="openCity(event, 'contactmap')">Contact Map</a></li>
    <li><a href="javascript:void(0)" class="tablinks" id="c2" 
           onclick="openCity(event, 'patternmap')">Direct</a></li>
    <li><a href="javascript:void(0)" class="tablinks" id="c3" 
           onclick="openCity(event, 'regulatory')">Regulatory</a></li>
  </ul>
 

  <div id="contactmap" class="tabcontent tclass01">
    <h3>Contact Map</h3>
    <p>Here's a nice description of what a contact map is. (Link to paper.) </p>
  </div>
 

  <div id="patternmap" class="tabcontent tclass02a">
    <h3>All Rules</h3>
    <p>Please click a line number in the editor to see a specific rule.
       (Link to paper.)</p>
  </div>
  <div id="patternmap" class="tabcontent tclass02b">
    <p> <font size="+1"><input type="button" onclick="setForType()"   
        style="background-color: #ddd" value="View Direct Forward Rule"></font>
        <font size="+1"><input type="button" onclick="set4ForType()"   
        style="background-color: #ddd" value="View Compact Forward Rule"></font>
    </p>
    <h3><div id="rule_div02b"></div></h3>
  </div>
  <div id="patternmap" class="tabcontent tclass02c">
      <table border="0" cellpadding="4" cellspacing="4">
      <tr><td>
        <font size="+1"><input type="button" onclick="setForType()"   
        style="background-color: #ddd" value="View Direct Forward Rule"></font>
      </td><td>
        <font size="+1"><input type="button" onclick="set4ForType()"   
        style="background-color: #ddd" value="View Compact Forward Rule"></font>
      </td></tr>
      <tr><td>
        <font size="+1"><input type="button" onclick="setRevType()"   
        style="background-color: #ddd" value="View Direct Reverse Rule"></font>
      </td><td>
        <font size="+1"><input type="button" onclick="set4RevType()"   
        style="background-color: #ddd" value="View Compact Reverse Rule"></font>
      </td></tr>
      </table>
  
    <h3><div id="rule_div02c"></div></h3>
  </div>

 
  <div id="regulatory" class="tabcontent tclass03a">
    <h3>Regulatory</h3>
    <p>Here's a nice description of what an oization operation map is.
      The time has come for all good men to come to the aid of their coutnry.
      (Link to paper.)
    </p>
  </div>
  <div id="regulatory" class="tabcontent tclass03b">
    <p> <font size="+1"><input type="button" onclick="setForType()"   
        style="background-color: #ddd" value="View Forward Rule"></font></p>
    <h3><div id="rule_div03b"></div></h3>
  </div>
  <div id="regulatory" class="tabcontent tclass03c">
    <p> <font size="+1"><input type="button" onclick="setForType()"   
        style="background-color: #ddd" value="View Forward Rule"></font>
        <font size="+1"><input type="button" onclick="setRevType()"   
        style="background-color: #ddd" value="View Reverse Rule"></font></p>
    <h3><div id="rule_div03c"></div></h3>
  </div>
</div>             <!-- row 1 of col 2 -->
<!-- margin parameters: top, right, bottom, left -->
<!-- margin was  200 20 20 20 -->
<!-- height is normally 550px -->
<div id="cy" class="row" 
  style="position:absolute; width:650px; height:250px; margin:200px 20px 20px 40px"> 
</div>
 <!-- row 2 of col 2 -->
<!--  
    <div id="cy" style="margin:200px 0px 0px 20px"></div>
<div class="main" id="cy" style="display: inline;border-radius: 25px;border: 5px solid #73AD21;background-color:#FFFFFF;padding: 0px 0px;margin:200px 0px 0px 800px;float:right;height:600px;width:550px"> </div>  -->
<!-- </div> -->


<div class="tabbed skin-belize-hole round">
  <ul>
    <li>Eighth  tab</li>
    <li>Seventh tab</li>
    <li>Sixth   tab</li>
    <li>Fifth   tab</li>
    <li>Fourth  tab</li>
    <li>Third   tab</li>
    <li>Second  tab</li>
    <li class="active">First tab</li>
  </ul>
</div>


</div> <!-- row 2 of col 2-->
</div> <!-- col 2-->

</div>  <!-- row -->
</div>  <!-- container -->







<!--
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<font color="white">
<ul>
<li><a name="pete1">This</a></li>
<li><a name="pete2">That</a></li>
<li><a name="pete3">The</a></li>
<li><a name="pete4">Other</a></li>
<li><a name="pete5">Thing</a></li>
</ul>

-->


<!-- javascript only -->
{% include "polls/edit_scripts.js" %}    


</font>
</body>
</html>

rulebender_online/polls/templates/polls/lines.html
<!--
<script>


function openCity(evt, cityName) {
    // Declare all variables
    var i, tabcontent, tablinks;

    // Get all elements with class="tabcontent" and hide them
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }

    // Get all elements with class="tablinks" and remove the class "active"
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    // Show the current tab, and add an "active" class to the link that opened the tab
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
    cy.resize();
}

</script>
-->

rulebender_online/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>